# Generated by Django 5.2 on 2025-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('month', models.DateField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
