# Generated by Django 5.2 on 2025-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.TextField()),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial')], max_length=20)),
                ('offer_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('land_area', models.FloatField()),
                ('floor_area', models.FloatField()),
                ('floors', models.IntegerField()),
                ('age_of_building', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('parking', models.BooleanField(default=False)),
                ('furnishing_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_tel', models.CharField(max_length=15)),
                ('seller_email', models.EmailField(max_length=254)),
                ('images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('property_features', models.ManyToManyField(blank=True, to='home.propertyfeature')),
            ],
        ),
    ]
