# Generated by Django 5.2 on 2025-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pendingad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingAd',
        ),
    ]
