# Generated by Django 5.2 on 2025-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_pendingad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=50)),
                ('offer_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Land', 'Land'), ('Commercial', 'Commercial'), ('Bungalow', 'Bungalow'), ('Villa', 'Villa'), ('Annexe', 'Annexe'), ('Rooms', 'Rooms'), ('Studio', 'Studio')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floor_area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(default='Per Month', max_length=20)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available Now', 'Available Now'), ('Available Soon', 'Available Soon'), ('Offer Received', 'Offer Received'), ('Price Reduced', 'Price Reduced')], max_length=50)),
                ('age_of_building', models.IntegerField(blank=True, null=True)),
                ('furnishing_status', models.CharField(blank=True, choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='pending_property_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_features', models.ManyToManyField(blank=True, to='home.propertyfeature')),
            ],
        ),
    ]
