# Generated by Django 5.2 on 2025-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pendingad_age_of_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingad',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='confirmed_ownership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='furnishing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='offer_type',
            field=models.CharField(default='Rent', max_length=10),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='floor_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='price_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_property_images/'),
        ),
        migrations.AlterField(
            model_name='pendingad',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
