# Generated by Django 5.2 on 2025-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pendingad_age_pendingad_confirmed_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingad',
            name='registered_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='registered_district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='registered_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pendingad',
            name='registered_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
