# Generated by Django 5.2 on 2025-04-21 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_confirmedad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 21, 18, 0)),
            preserve_default=False,
        ),
    ]
