# Generated by Django 5.2 on 2025-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmedad',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='pendingad',
            name='confirmed_ownership',
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='price_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='confirmedad',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='confirmedad',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
