# Generated by Django 5.2 on 2025-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_name_confirmedad_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingad',
            name='confirmed_ownership',
            field=models.BooleanField(default=False),
        ),
    ]
