# Generated by Django 5.2 on 2025-04-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_pendingad_confirmed_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=10)),
                ('price_index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LandPriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=10)),
                ('price_index', models.FloatField()),
            ],
        ),
    ]
