# Generated by Django 5.2 on 2025-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_housepriceindex_landpriceindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedad',
            name='images',
        ),
        migrations.RemoveField(
            model_name='pendingad',
            name='property_image',
        ),
        migrations.CreateModel(
            name='ConfirmedAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='confirmed_ad_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.confirmedad')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pending_ad_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pending_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.pendingad')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
